# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87d4e654de2297d8817d12423c3f10f60a08d918089021ccb6830e2e009941927ebe04b7bf37335adced5a51304a134ce7d6a98847429e7f67ad1ef9c8079088

test:
  secret_key_base: 6d595d798ae47cda6d5aca04a0f6f649ffcce92f091766e9a1e586a6da4abc4b2c5c7a0802cf4a62b2528677737916ef7ac3a20377c6caa5369414760dfd28af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
